### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by jimmyhmiller** [plandes/tabres#1]
The license clojure is distributed under (EPL) is not compatible with the GPL. This looks like a very awesome library, but the license issue means that I could not use it. Would you consider changing the license. 

([Here's an example](https://github.com/magnars/prone/issues/28) of a library that ran into this in the past)

**Comment by plandes** [comment]
@jimmyhmiller  Sure, I can do that.  Almost everything else I have on GitHub uses the Apache OS license.  Would that work?

**Comment by jimmyhmiller** [comment]
Yeah an Apache license would be great. Thanks!

**Comment by plandes** [comment]
Done.  Also the repo is current per Zensols build documentation is now up as well.  Please note the new version number.  Please let me know if I missed anything--that is the each source file had the License per typical GPL form, but I think I got them all.  (That said I used an Emacs keyboard macro to remove them.).  Closing this for now but we can reopen if there's any other mods you need.
